apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-test-job
  namespace: kai-test
spec:
  template:
    metadata:
      labels:
        runai/queue: test
    spec:
      schedulerName: kai-scheduler
      restartPolicy: OnFailure
      containers:
      - name: main
        image: nvidia/cuda:11.6.2-base-ubuntu20.04
        command: ["bash", "-c"]
        args: ["nvidia-smi; sleep 60"]
        resources:
          limits:
            nvidia.com/gpu: "1"