apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
  namespace: kai-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-serving
  template:
    metadata:
      labels:
        app: model-serving
        runai/queue: test
    spec:
      schedulerName: kai-scheduler
      containers:
      - name: serving
        image: nvcr.io/nvidia/tensorrt:23.08-py3
        command: ["python", "-c"]
        args: [
          "import torch; import time; print('CUDA available:', torch.cuda.is_available()); print('GPU device count:', torch.cuda.device_count()); print('GPU device name:', torch.cuda.get_device_name(0)); print('Starting model server...'); while True: time.sleep(60)"
        ]
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            memory: "4Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: kai-test
spec:
  selector:
    app: model-serving
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP